(in-package :cl-logo.examples)

(defcmd flower (ht w h)
  (let* ((xy (current-pos))
         (x (car xy))
         (y (cdr xy))
         (xc (- x (/ w 2)))
         (yc (+ y ht))
         (xp1 (- x (/ (* 3 w) 2)))
         (yp1 (+ y (- ht h)))
         (xp2 xp1)
         (yp2 (+ y ht h))
         (xp3 (+ x (/ w 2)))
         (yp3 yp2)
         (xp4 xp3)
         (yp4 yp1))
    (up ht)
    (move-to xc yc)
    (rectangle w h)
    (move-to xp1 yp1)
    (rectangle w h)
    (move-to xp2 yp2)
    (rectangle w h)
    (move-to xp3 yp3)
    (rectangle w h)
    (move-to xp4 yp4)
    (rectangle w h)
    (move-to x y)))
