(in-package :cl-logo.examples)

(defcmd robot (w h)
  "Draw a simplistic robot face based on rectangles"
  (let* ((xy (current-pos))
         (x-orig (car xy))
         (y-orig (cdr xy))
         (w-mouth (/ w 3))
         (h-mouth (/ h 6))
         (x-mouth (+ x-orig (/ (- w w-mouth) 2)))
         (y-mouth y-orig)
         (w-eye (/ w 5))
         (h-eye (/ h 5))
         (space-bw-eyes (/ (- w (+ w-eye w-eye)) 3))
         (x-left-eye (+ x-orig space-bw-eyes))
         (y-left-eye (+ y-orig (- h h-eye)))
         (x-right-eye (+ x-left-eye w-eye space-bw-eyes))
         (y-right-eye y-left-eye))
    (rectangle w h)
    (move-to x-mouth y-mouth)
    (rectangle w-mouth h-mouth)
    (move-to x-left-eye y-left-eye)
    (rectangle w-eye h-eye)
    (move-to x-right-eye y-right-eye)
    (rectangle w-eye h-eye)
    (move-to x-orig y-orig)))
